---
asyncapi: 3.0.0
info:
  title: IATI Internal Message Queue Service Common Components - Messages
  version: 0.2.0
  description: |
    Definition of messages needed by apps using the IATI internal message queue
    service.

defaultContentType: application/json

components:
  messages:
    dataset_created:
      name: dataset_created
      title: Notification that a dataset has been created.
      summary: |
        Message indicating that a dataset record has been deleted on the
        Registry. The `message_id` in this spec serves to identify the
        message type is not itself part of the message, but this message must
        contain an application header called `message_type` that contains the
        `DATASET_CREATED` in uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "DATASET_CREATED"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - dataset
          - dataset_action
        properties:
          message_type:
            type: string
            const: "DATASET_CREATED"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          dataset:
            $ref: "#/components/schemas/dataset"
          dataset_actions:
            $ref: "#/components/schemas/dataset_action_list"
      examples:
        - name: created_example
          payload:
            message_type: "DATASET_CREATED"
            message_date: "2025-06-27T06:54:20+00:00"
            dataset:
              id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              short_name: "aidagcy-activity-3"
              human_readable_name: "Aid Agency - Activity 3"
              source_type: "primary_source"
              licence_id: "gpl-3.0"
              url: "https://www.example.org/datasets/activity3.xml"
              last_url_update_date: "2025-06-27T06:54:20+00:00"
              last_metadata_update_date: "2025-06-27T06:54:20+00:00"
              reporting_org_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              reporting_org_short_name: "aidagcy"
            dataset_actions:
              - id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                dataset_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                action_type: "create"
                created_date: "2025-06-27T06:54:20+00:00"
                responsible_org_id: "1064831d-019d-47f9-a87d-9605d93400d6"
                responsible_org_name: "Aid Agency South"
                user_application_id: "dd80e2e6-ee42-4da6-bfc6-e585480d34a9"
                user_application_name: "Register Your Data WebApp"
                user_name: "John Smith"
                user_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"

    dataset_updated:
      name: dataset_updated
      title: Notification that a dataset has been updated.
      summary: |
        Message indicating that a dataset record has been deleted on the
        Registry. The `message_id` in this spec serves to identify the message
        type is not itself part of the message, but this message must contain an
        application header called `message_type` that contains the
        `DATASET_UPDATED` in uppercase. Note: a single user operation to update
        their dataset may result in multiple dataset actions being recorded
        because the updating of urls and the visibility status are logged
        separately.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "DATASET_UPDATED"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - dataset
          - dataset_action
        properties:
          message_type:
            type: string
            const: "DATASET_UPDATED"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          dataset:
            $ref: "#/components/schemas/dataset"
          dataset_actions:
            $ref: "#/components/schemas/dataset_action_list"
      examples:
        - name: update that changes url only
          payload:
            message_type: "DATASET_UPDATED"
            message_date: "2025-06-27T06:54:20+00:00"
            dataset:
              id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              short_name: "aidagcy-activity-3"
              human_readable_name: "Aid Agency - Activity 3 Update"
              source_type: "primary_source"
              licence_id: "gpl-3.0"
              url: "https://www.example.org/datasets/activity3.xml"
              last_url_update_date: "2025-06-27T06:54:20+00:00"
              last_metadata_update_date: "2025-06-27T06:54:20+00:00"
              reporting_org_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              reporting_org_short_name: "aidagcy"
            dataset_actions:
              - id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                dataset_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                action_type: "update_url"
                created_date: "2025-06-27T06:54:20+00:00"
                responsible_org_id: "1064831d-019d-47f9-a87d-9605d93400d6"
                responsible_org_name: "Aid Agency South"
                user_application_id: "dd80e2e6-ee42-4da6-bfc6-e585480d34a9"
                user_application_name: "Register Your Data WebApp"
                user_name: "John Smith"
                user_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
        - name: update that changes url and other fields
          payload:
            message_type: "DATASET_UPDATED"
            message_date: "2025-06-27T06:54:20+00:00"
            dataset:
              id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              short_name: "aidagcy-activity-3"
              source_type: "primary_source"
              licence_id: "gpl-3.0"
              url: "https://www.example.org/datasets/activity3.xml"
              last_url_update_date: "2025-06-27T06:54:20+00:00"
              last_metadata_update_date: "2025-06-27T06:54:20+00:00"
              reporting_org_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              reporting_org_short_name: "aidagcy"
            dataset_actions:
              - id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                dataset_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                action_type: "update_url"
                created_date: "2025-06-27T06:54:20+00:00"
                responsible_org_id: "1064831d-019d-47f9-a87d-9605d93400d6"
                responsible_org_name: "Aid Agency South"
                user_application_id: "dd80e2e6-ee42-4da6-bfc6-e585480d34a9"
                user_application_name: "Register Your Data WebApp"
                user_name: "John Smith"
                user_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              - id: "b52bc269-0595-4814-8075-eccfece49dd9"
                dataset_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                action_type: "update_metadata"
                created_date: "2025-06-27T06:54:20+00:00"
                responsible_org_id: "1064831d-019d-47f9-a87d-9605d93400d6"
                responsible_org_name: "Aid Agency South"
                user_application_id: "dd80e2e6-ee42-4da6-bfc6-e585480d34a9"
                user_application_name: "Register Your Data WebApp"
                user_name: "John Smith"
                user_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"

    dataset_deleted:
      name: dataset_deleted
      title: Notification that a dataset has been deleted.
      summary: |
        Message indicating that a dataset record has been deleted on the
        Registry. The `message_id` in this spec serves to identify the
        message type is not itself part of the message, but this message must
        contain an application header called `message_type` that contains the
        `DATASET_DELETED` in uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "DATASET_DELETED"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - dataset
          - dataset_action
        properties:
          message_type:
            type: string
            const: "DATASET_DELETED"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          dataset:
            type: object
            required:
              - id
            properties:
              id:
                type: string
                format: uuid
                example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
          dataset_actions:
            $ref: "#/components/schemas/dataset_action_list"
      examples:
        - name: A dataset deleted example
          payload:
            message_type: "DATASET_DELETED"
            message_date: "2025-06-27T06:54:20+00:00"
            dataset:
              id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              short_name: "aidagcy-activity-3"
              human_readable_name: "Aid Agency - Activity 3"
              source_type: "primary_source"
              licence_id: "gpl-3.0"
              url: "https://www.example.org/datasets/activity3.xml"
              last_url_update_date: "2025-06-27T06:54:20+00:00"
              last_metadata_update_date: "2025-06-27T06:54:20+00:00"
              reporting_org_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              reporting_org_short_name: "aidagcy"
            dataset_actions:
              - id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                dataset_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                action_type: "delete"
                created_date: "2025-06-27T06:54:20+00:00"
                responsible_org_id: "1064831d-019d-47f9-a87d-9605d93400d6"
                responsible_org_name: "Aid Agency South"
                user_application_id: "dd80e2e6-ee42-4da6-bfc6-e585480d34a9"
                user_application_name: "Register Your Data WebApp"
                user_name: "John Smith"
                user_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"

    reporting_org_created:
      name: reporting_org_created
      title: Notification that a reporting org has been created.
      summary: |
        Message indicating that a dataset record has been deleted on the
        Registry. The `message_id` in this spec serves to identify the
        message type is not itself part of the message, but this message must
        contain an application header called `message_type` that contains the
        `REPORTING_ORG_CREATED` in uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "REPORTING_ORG_CREATED"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - reporting_org
          - reporting_org_action
        properties:
          message_type:
            type: string
            const: "REPORTING_ORG_CREATED"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          reporting_org:
            $ref: "#/components/schemas/reporting_org"
          reporting_org_actions:
            $ref: "#/components/schemas/reporting_org_action_list"
      examples:
        - name: created_example
          payload:
            message_type: "REPORTING_ORG_CREATED"
            message_date: "2025-06-27T06:54:20+00:00"
            reporting_org:
              created_date: "2025-06-27T06:54:20+00:00"
              data_portal_url: "https://data.example.org/organizations/aidagcy"
              default_license_id: "gpl-3.0"
              description: "Aid Agency Country Y is an international aid agency."
              exclusions_policy_url: "https://www.example.org/aidagcy/exclusions"
              first_publication_date: "2025-06-27T06:54:20+00:00"
              hq_country_code: "YY"
              human_readable_name: "Aid Agency Country Y"
              id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
              organisation_identifier: "GB-AID-AGCY"
              organisation_type: "10"
              region: "88"
              reporting_source_type: "primary_source"
              short_name: "aidagcy"
              website_url: "https://www.example.org/aidagcy"
            reporting_org_actions:
              - id: "2e60bb06-0d48-4683-a03e-1d8d1e566fdc"
                reporting_org_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                action_type: "create"
                created_date: "2025-06-27T06:54:20+00:00"
                responsible_org_id: "5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8"
                responsible_org_name: "Aid Agency South"
                user_application_id: "dd80e2e6-ee42-4da6-bfc6-e585480d34a9"
                user_application_name: "Register Your Data WebApp"
                user_name: "John Smith"
                user_id: "83baecf7-771c-474b-a561-50af49d0e0ec"

    reporting_org_updated:
      name: reporting_org_updated
      title: Notification that a reporting org has been updated.
      summary: |
        Message indicating that a reporting_org record has been updated on the
        Registry. The `message_id` in this spec serves to identify the
        message type is not itself part of the message, but this message must
        contain an application header called `message_type` that contains the
        `REPORTING_ORG_UPDATED` in uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "REPORTING_ORG_UPDATED"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - reporting_org
          - reporting_org_action
        properties:
          message_type:
            type: string
            const: "REPORTING_ORG_UPDATED"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          reporting_org:
            $ref: "#/components/schemas/reporting_org"
          reporting_org_actions:
            $ref: "#/components/schemas/reporting_org_action_list"

    reporting_org_deleted:
      name: reporting_org_deleted
      title: Notification that a reporting org has been deleted.
      summary: |
        Message indicating that a reporting_org record has been deleted on the
        Registry. The `message_id` in this spec serves to identify the
        message type is not itself part of the message, but this message must
        contain an application header called `message_type` that contains the
        `REPORTING_ORG_DELETED` in uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "REPORTING_ORG_DELETED"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - reporting_org
          - reporting_org_action
        properties:
          message_type:
            type: string
            const: "REPORTING_ORG_DELETED"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          reporting_org:
            type: object
            required:
              - id
            properties:
              id:
                type: string
                format: uuid
                example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
          reporting_org_actions:
            $ref: "#/components/schemas/reporting_org_action_list"

    dataset_check_result:
      name: dataset_check_result
      title: The result of a dataset download check.
      summary: |
        Message describing the result of a Bulk Data Service dataset check. The
        `message_id` in this spec serves to identify the message type is not
        itself part of the message, but this message must contain an application
        header called `message_type` that contains the `DATASET_CHECK_RESULT` in
        uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "DATASET_CHECK_RESULT"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - dataset_check_result_current
        properties:
          message_type:
            type: string
            const: "DATASET_CHECK_RESULT"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          dataset_check_result_current:
            $ref: "#/components/schemas/dataset_check_result"
          dataset_check_result_previous:
            $ref: "#/components/schemas/dataset_check_result"

    dataset_download_attempt_result:
      name: dataset_download_attempt_result
      title: The result of a full dataset download check.
      summary: |
        Message describing the result of a Data Downloader dataset download
        attempt. The `message_id` in this spec serves to identify the message
        type is not itself part of the message, but this message must contain an
        application header called `message_type` that contains the `_RESULT` in
        uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "DATASET_DOWNLOAD_ATTEMPT_RESULT"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - dataset_download_attempt_result
        properties:
          message_type:
            type: string
            const: "DATASET_DOWNLOAD_ATTEMPT_RESULT"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          dataset_download_attempt_result:
            $ref: "#/components/schemas/dataset_download_attempt_result"

    dataset_download_request:
      name: dataset_download_request
      title: |
        Request for a full download attempt to be made on the specified dataset.
      summary: |
        Message requesting that a full download attempt be made for the
        specified dataset. The `message_id` in this spec serves to identify the
        message type is not itself part of the message, but this message must
        contain an application header called `message_type` that contains the
        `DATASET_DOWNLOAD_REQUEST` in uppercase.
      headers:
        type: object
        properties:
          message_type:
            type: string
            const: "DATASET_DOWNLOAD_REQUEST"
            description: |
              This is set as a key/value pair as the custom application headers
              (in the Azure library it's the `application_properties`
              parameter).
      payload:
        type: object
        required:
          - message_type
          - message_date
          - dataset_download_request
        properties:
          message_type:
            type: string
            const: "DATASET_DOWNLOAD_REQUEST"
          message_date:
            type: string
            format: date-time
            example: 2025-06-27T06:54:20+00:00
          dataset:
            $ref: "#/components/schemas/dataset"
          dataset_hash_details:
            $ref: "#/components/schemas/dataset_hash_details"

  schemas:
    dataset:
      title: An IATI Registry dataset record.
      type: object
      required:
        - id
        - short_name
        - human_readable_name
        - source_type
        - url
        - last_url_update_date
        - last_metadata_update_date
        - licence_id
        - reporting_org_id
        - reporting_org_short_name
      properties:
        id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        short_name:
          type: string
          example: aidagcy-activity-3
        human_readable_name:
          type: string
          example: Aid Agency - Activity File 3
        source_type:
          type: string
          enum:
            - primary_source
            - secondary_source
          example: primary_source
        licence_id:
          type: string
          example: gpl-3.0
        url:
          type: string
          format: url
          example: https://www.example.org/datasets/activity3.xml
        last_url_update_date:
          type: string
          format: date-time
          example: 2025-06-27T06:54:20+00:00
        last_metadata_update_date:
          type: string
          format: date-time
          example: 2025-06-27T06:54:20+00:00
        reporting_org_id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        reporting_org_short_name:
          type: string
          example: aidagcy

    dataset_action:
      title: An action taken on an IATI Registry dataset record.
      type: object
      required:
        - id
        - created_date
        - dataset_id
        - action_type
        - responsible_org_id
        - responsible_org_name
        - user_application_id
        - user_application_name
        - user_id
        - user_name
      properties:
        id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        created_date:
          type: string
          format: date-time
          example: 2025-06-27T06:54:20+00:00
        dataset_id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        action_type:
          type: string
          enum:
            - create
            - update_metadata
            - update_url
            - update_visibility
            - delete
          example: update_url
        responsible_org_id:
          type: string
          format: uuid
          example: 1064831d-019d-47f9-a87d-9605d93400d6
        responsible_org_name:
          type: string
          example: Aid Agency South
        user_application_id:
          type: string
          format: uuid
          example: dd80e2e6-ee42-4da6-bfc6-e585480d34a9
        user_application_name:
          type: string
          example: Register Your Data WebApp
        user_name:
          type: string
          format: name
          example: John Smith
        user_id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8

    dataset_action_list:
      title: A list of IATI Registry dataset actions.
      type: array
      items:
        $ref: "#/components/schemas/dataset_action"

    reporting_org:
      description: An IATI Registry reporting_org record (without contact info).
      type: object
      properties:
        created_date:
          type: string
          format: date-time
          example: '2023-08-27T07:31:06+00:00'
          nullable: true
        data_portal_url:
          type: string
          format: url
          example: 'https://www.example.org/data-portal'
          nullable: true
        default_licence_id:
          type: string
          example: gpl-3.0
          nullable: true
        description:
          type: string
          example: |
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          nullable: true
        exclusions_policy_url:
          type: string
          format: url
          example: 'https://www.example.org/exclusions-policy'
          nullable: true
        first_publication_date:
          type: string
          format: date-time
          example: '2025-06-27T07:31:06+00:00'
          nullable: true
        hq_country:
          description: |
            This is a codelist field. Valid values come from the code list:
            https://iatistandard.org/en/iati-standard/203/codelists/country/
          type: string
          example: GB
          nullable: true
        human_readable_name:
          type: string
          example: Aid Agency
          nullable: false
        id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
          nullable: false
        organisation_identifier:
          type: string
          example: CO-ABC-123456
          nullable: true
        organisation_type:
          description: |
            This is a codelist field. Valid values come from the code list:
            https://iatistandard.org/en/iati-standard/203/codelists/organisationtype/
          type: string
          example: 23
          nullable: true
        region:
          description: |
            This is a codelist field. Valid values come from the code list:
            https://iatistandard.org/en/iati-standard/203/codelists/region/
          type: string
          example: 889
          nullable: true
        reporting_source_type:
          type: string
          example: primary_source
          enum:
            - primary_source
            - secondary_source
          nullable: true
        short_name:
          type: string
          example: aidagcy
          nullable: false
        website:
          type: string
          format: url
          example: 'https://www.example.org/'
          nullable: true
      required:
        - created_date
        - data_portal_url
        - default_licence_id
        - description
        - exclusions_policy_url
        - first_publication_date
        - hq_country
        - human_readable_name
        - id
        - organisation_identifier
        - organisation_type
        - region
        - reporting_source_type
        - short_name
        - website
    reporting_org_action:
      title: An action taken on an IATI Registry reporting org record.
      type: object
      required:
        - action_type
        - created_date
        - id
        - reporting_org_id
        - user_application
        - user_name
        - user_id
      properties:
        action_type:
          type: string
          enum:
            - create
            - update
            - delete
          example: update
        created_date:
          type: string
          format: date-time
          example: 2025-06-27T06:54:20+00:00
        id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        reporting_org_id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8
        user_application:
          type: string
          example: Register Your Data WebApp
        user_name:
          type: string
          format: name
          example: John Smith
        user_id:
          type: string
          format: uuid
          example: 5401c7f4-e9fd-4ce3-b184-bfe1cb71a9f8

    reporting_org_action_list:
      title: A list of IATI Registry reporting org actions.
      type: array
      items:
        $ref: "#/components/schemas/reporting_org_action"

    dataset_head_request_attempt_result:
      title: |
        A message schema which details the results of a HEAD attempt by the Bulk
        Data Service.
      type: object
      properties:
        datetime:
          description: |
            The time of the `HEAD` request. `HEAD` requests are only made when
            the `source_url` is unchanged and the dataset has been successfully
            downloaded in the last ~72 hours. This means that the time of the
            most recent `HEAD` request may not be the same as the
            `last_update_check`.
          type: string
          format: date-time
          example: 2025-06-27T07:31:06+00:00
        error_details:
          type: object
          required:
            - error_type
          properties:
            detailed_message:
              type: string
              description: |
                A detailed error message, often produced by the relevant
                component library.
              example: |
                "requests.exceptions.ConnectionError:
                HTTPConnectionPool(host='www.iatistandard.com', port=80): Max
                retries exceeded with url: / (Caused by
                NameResolutionError(\"<urllib3.connection.HTTPConnection object
                at 0x74b4aecaa9c0>: Failed to resolve 'www.iatistandard.com'
                ([Errno -2] Name or service not known)\"))"
            error_type:
              description: |
                The type of error that occurred. `other_error` indicates any
                connection error not listed that resulted in there not being a
                valid HTTP response.
              type: string
              enum:
                - connection_error
                - connection_timeout
                - too_many_redirects
                - ssl_error
                - other_error
                - http_non_200
            http_method:
              type: string
              const: HEAD
            http_reason:
              type: string
              example: Not Found
            http_status:
              type: string
              format: int
              example: 404
            http_headers:
              type: object
            summary_message:
              type: string
              description: A succinct message from the relevant IATI app.
              example: Download attempt failed due to connection timeout
            source_url:
              description: |
                The URL which caused the error. Note that this may not be the
                same as the current value of `source_url` because if the
                dataset's registered source_url is updated then the Bulk Data
                Service proceeds straight to a full download attempt and does
                not attempt a `HEAD` request.
              type: string
              format: url
              example: https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
        error_occurred:
          type: boolean
          description: |
            Indicates whether or not the `HEAD` resulted in an error. It will be
            true if either there was a problem completing the HTTP connection,
            or if the HTTP response was non-200. False implies `http_status` is
            200.
        http_status:
          type: string
          description: |
            The 'http_status' field provides the HTTP status code regardless of
            outcome.
          format: int
          example: 200

    dataset_get_request_attempt_result:
      title: |
        A message schema which details the results of a GET attempt by the Bulk
        Data Service or Data Downloader (eventually, the Data Downloader will be
        responsible for all GET requests, but in the meantime the Bulk Data
        Service will still be doing the noraml GET checks).
      type: object
      properties:
        datetime:
          type: string
          format: date-time
          example: 2025-06-27T07:31:06+00:00
        error_details:
          type: object
          properties:
            detailed_message:
              type: string
              description: |
                A detailed error message, often produced by the relevant
                component library.
              example: |
                "requests.exceptions.ConnectionError:
                HTTPConnectionPool(host='www.iatistandard.com', port=80): Max
                retries exceeded with url: / (Caused by
                NameResolutionError(\"<urllib3.connection.HTTPConnection object
                at 0x74b4aecaa9c0>: Failed to resolve 'www.iatistandard.com'
                ([Errno -2] Name or service not known)\"))"
            error_type:
              type: string
              description: |
                Gives details of the error encountered when making the `GET``
                request. The value `not_iati_content` indicates that a file was
                succcessfully downloaded (such that `http_status` will be 200)
                but that it was not an IATI XML file.
              enum:
                - connection_error
                - connection_timeout
                - too_many_redirects
                - ssl_error
                - other_error
                - http_non_200
                - not_iati_content
            http_method:
              type: string
              const: GET
            http_reason:
              type: string
              example: Not Found
            http_status:
              type: string
              description: |
                **Note:** A status of 200 indicates a successful download of
                some file or other, but the download result could still be in an
                error state if the file downloaded is not a valid IATI XML file.
                For this reason, the `error_occurred` field on the parent object
                should be used for determining error status.
              format: int
              example: 404
            http_headers:
              type: object
            summary_message:
              type: string
              description: A succinct message from the relevant IATI app.
              example: Download attempt failed due to connection timeout
            source_url:
              description: |
                The url which produced the `GET` error. Note that this may not
                be the same as the current value of `source_url` because the
                `source_url` may have recently been updated and there may not
                yet be any download results for the new url.
              type: string
              format: url
              example: https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
        error_occurred:
          type: boolean
          description: |
            Indicates whether or not the `GET` request resulted in the
            _**successful download of an IATI XML file**_. This means that an
            HTTP status of 200 does not necessarily indicate success. For this
            reason, this field should be used to determine success status.
        http_status:
          type: string
          description: |
            An `http_status` of 200 does not necessarily mean an IATI
            dataset has been successfully downloaded, because the file
            downloaded may not have been an IATI XML file. For this reason, the
            `error_occurred` field should be used to determine success.
          format: int
          example: 200

    dataset_hash_details:
      title: Dataset hash
      type: object
      properties:
        hash:
          type: string
          example: 041c7dba17b9356be78edc99016d337aa7c33f3a
        hash_excluding_generated_timestamp:
          type: string
          example: 738a1ad14dca2451fa89e642b753101dcf57ce2f

    dataset_download_details:
      title: Details of a successful download of a dataset.
      type: object
      properties:
        cached_dataset_xml_url:
          type: string
          format: url
          example: https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.xml
        cached_dataset_xml_etag:
          type: string
          example: '"HXCCHBNTLJWWBB"'
        cached_dataset_zip_url:
          type: string
          format: url
          example: https://bulk-data.iatistandard.org/aidagcy/aidagcy-activity-3.zip
        cached_dataset_zip_etag:
          type: string
          example: '"C1362D1244MWNQ"'
        content_length:
          type: string
          format: int
          example: 1612475
        downloaded:
          type: string
          format: date-time
          example: 2025-06-27T07:31:06+00:00
        hash:
          type: string
          example: 041c7dba17b9356be78edc99016d337aa7c33f3a
        hash_excluding_generated_timestamp:
          type: string
          example: 738a1ad14dca2451fa89e642b753101dcf57ce2f
        initial_contents:
          type: string
          example: |
            <iati-activities version="2.03"
            generated-datetime="2025-07-23T20:06:02"><iati-activity
            xml:lang="en" d
        server_header_etag:
          type: string
          example: '"KXDMHBNCLJWWUV"'
        server_header_last_modified:
          type: string
          format: date-time
          example: 2025-06-27T07:31:06+00:00
        source_url:
          type: string
          format: url
          example: https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
        verified_on_server:
          type: string
          format: date-time
          example: 2025-06-27T07:31:06+00:00

    dataset_check_result:
      title: |
        An message which details the results of a Bulk Data Service check
        operation on the dataset.
      type: object
      required:
        - id
        - short_name
      properties:
        id:
          type: string
          format: uuid
          example: 22d82ca0-67de-11f0-90a9-a7bd7f82882f
        short_name:
          type: string
          example: aidagcy-activity-3
        reporting_org_id:
          type: string
          format: uuid
          example: de576bb9-5f2b-4d43-a570-53ab3b8bb9b8
        reporting_org_short_name:
          type: string
          example: aidagcy
        licence_id:
          type: string
        source_url:
          type: string
          format: url
          example: https://www.example.com/files/aidagcy/aidagcy-activity-file.xml
        last_update_check:
          description: |
            This field is updated every time the Bulk Data Service checks the
            dataset, regardless of whether a full download was attempted and
            regardless of the result.
          type: string
          format: date-time
          example: 2025-06-27T07:31:06+00:00

        last_known_good_dataset:
          $ref: "#/components/schemas/dataset_download_details"

        most_recent_head_attempt:
          $ref: "#/components/schemas/dataset_head_request_attempt_result"

        most_recent_get_attempt:
          $ref: "#/components/schemas/dataset_get_request_attempt_result"

    dataset_download_attempt_result:
      title: |
        An message which details the results of a full dataset download attempt.
      type: object
      required:
        - id
        - short_name
      properties:
        id:
          type: string
          format: uuid
          example: 22d82ca0-67de-11f0-90a9-a7bd7f82882f
        short_name:
          type: string
          example: aidagcy-activity-3
        dataset_download_details:
          $ref: "#/components/schemas/dataset_download_details"
        get_attempt_result:
          $ref: "#/components/schemas/dataset_get_request_attempt_result"
